apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dra-admission-webhook.configmapName" . }}
  namespace: {{ include "dra-admission-webhook.namespace" . }}
  labels:
    {{- include "dra-admission-webhook.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.webhookConfig | toYaml | nindent 4 }}
  reconciler.yaml: |
    {{- .Values.reconcilerConfig | toYaml | nindent 4 }}
