{{- if .Values.webhookPvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dra-admission-webhook.fullname" . }}-webhook-data
  namespace: {{ include "dra-admission-webhook.namespace" . }}
  labels:
    {{- include "dra-admission-webhook.webhookLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.webhookPvc.accessModes | nindent 4 }}
  {{- if .Values.webhookPvc.storageClassName }}
  storageClassName: {{ .Values.webhookPvc.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.webhookPvc.size }}
{{- end }}
