apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dra-webhook-system

resources:
- configmap.yaml
- rbac.yaml
- webhook-deployment.yaml
- webhook-service.yaml
- webhook-config.yaml
- reconciler-pvc.yaml
- reconciler-deployment.yaml
- webhook-pdb.yaml
